name: "hyperliquid"

services:
  node:
    restart: unless-stopped
    build: .
    image: hyperliquid-node:latest
    ports:
      - "4000-4010:4000-4010"
    entrypoint: "/home/hluser/hl-visor run-validator"
    volumes:
      - /home/hyperliquid/hl/data:/home/hluser/hl/data
      - /home/hyperliquid/hl/hyperliquid_data:/home/hluser/hl/hyperliquid_data
